FROM oven/bun:1 AS base

WORKDIR /usr/src/app

COPY ./agent ./agent
COPY ./fe ./fe
COPY ./history ./history
COPY ./packages ./packages
COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json


RUN bun install --filter history --filter packages
RUN bun run generate:db

EXPOSE 8081

CMD ["bun","start:history"]