FROM oven/bun:1 AS base

WORKDIR /usr/src/app

COPY ./agent ./agent
COPY ./fe ./fe
COPY ./history ./history
COPY ./packages ./packages
COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json


RUN bun install
RUN bun run generate:db
RUN bun build:frontend

EXPOSE 3000

CMD ["bun","start:frontend"]