FROM node:22-alpine

WORKDIR /usr/src/app

RUN npm install -g bun

COPY ./agent ./agent
COPY ./fe ./fe
COPY ./history ./history
COPY ./packages ./packages
COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json

RUN bun install --filter agent

EXPOSE 8080

CMD ["bun","start:agent"]